version: '3.0'
services:
  postgres-db:
    container_name: postgres-wino
    image: postgres
    ports:
      - 5432:5432
    networks:
      - wino-net

  rabbitmq-management:
    container_name: rabbitmq-wino
    image: rabbitmq:3-management
    ports:
      - 5432:5432
      - 15672:15672
    networks:
      - wino-net

networks:
  wino-net:
    driver: bridge
